import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { formatKrw, formatKrwInput, parseKrwAmount } from "@/lib/bidAnalysis";
import { buildBidScenarios, calculateBidFloor } from "@/lib/bidScenario";
import { AlertTriangle, ChartNoAxesCombined, CircleDollarSign, TableProperties } from "lucide-react";
import React from "react";

type Result = { baseAmount: number; lowRate: number; medianRate: number; highRate: number };
type TrendPoint = { date: string; averageRate: number; count: number };

export function CostMarginInputs({ costAmount, targetMarginRate, onCostAmountChange, onTargetMarginChange }: { costAmount: string; targetMarginRate: string; onCostAmountChange: (value: string) => void; onTargetMarginChange: (value: string) => void }) {
  const floor = calculateBidFloor(parseKrwAmount(costAmount), Number(targetMarginRate));
  return <div className="rounded-xl border border-amber-200 bg-amber-50/60 p-4 dark:border-amber-900/60 dark:bg-amber-950/20"><div className="mb-3 flex flex-wrap items-start justify-between gap-2"><div><p className="flex items-center gap-2 font-medium"><CircleDollarSign className="h-4 w-4 text-amber-700 dark:text-amber-400" />원가·목표 마진 하한선</p><p className="mt-1 text-xs text-muted-foreground">목표 마진은 매출총이익률 기준입니다. 하한선은 <strong>원가 ÷ (1 - 목표 마진율)</strong>로 계산합니다.</p></div>{floor ? <Badge className="bg-amber-700 hover:bg-amber-700">하한선 {formatKrw(floor)}</Badge> : <Badge variant="secondary">원가와 마진을 입력하세요</Badge>}</div><div className="grid gap-3 sm:grid-cols-2"><div className="space-y-1"><Label htmlFor="analysis-cost">총원가(원)</Label><Input id="analysis-cost" inputMode="numeric" value={costAmount} onChange={event => onCostAmountChange(formatKrwInput(event.target.value))} placeholder="예: 80,000,000" /></div><div className="space-y-1"><Label htmlFor="analysis-target-margin">목표 마진율(%)</Label><Input id="analysis-target-margin" inputMode="decimal" value={targetMarginRate} onChange={event => onTargetMarginChange(event.target.value.replace(/[^0-9.]/g, ""))} placeholder="예: 15" /></div></div></div>;
}

export function ScenarioComparison({ result, costAmount, targetMarginRate }: { result: Result; costAmount: string; targetMarginRate: string }) {
  const cost = parseKrwAmount(costAmount); const margin = Number(targetMarginRate); const scenarios = buildBidScenarios({ costAmount: cost, targetMarginRate: margin, lowRate: result.lowRate, medianRate: result.medianRate, highRate: result.highRate, baseAmount: result.baseAmount });
  return <Card className="mt-5 border-0 shadow-sm"><CardHeader className="pb-2"><CardTitle className="flex items-center gap-2 text-base"><TableProperties className="h-4 w-4 text-primary" />투찰가 시나리오 비교</CardTitle><p className="text-xs font-normal text-muted-foreground">원가·마진 하한선과 과거 낙찰률 기준의 여러 가격대를 한 번에 비교합니다.</p></CardHeader><CardContent className="overflow-x-auto"><table className="w-full min-w-[600px] text-left text-sm"><thead className="border-b text-xs text-muted-foreground"><tr><th className="pb-2 font-medium">시나리오</th><th className="pb-2 font-medium">근거</th><th className="pb-2 font-medium text-right">투찰가</th><th className="pb-2 font-medium text-right">낙찰률</th><th className="pb-2 font-medium text-right">원가 기준 마진</th><th className="pb-2 pl-4 font-medium">설명</th></tr></thead><tbody>{scenarios.map(scenario => <tr key={scenario.key} className={scenario.key === "median" ? "border-b bg-primary/[0.045]" : "border-b"}><td className="py-3 font-medium">{scenario.name}</td><td className="py-3"><Badge variant={scenario.source === "원가·마진" ? "secondary" : "outline"}>{scenario.source}</Badge></td><td className="py-3 text-right font-semibold">{formatKrw(scenario.price)}</td><td className="py-3 text-right">{scenario.rate ? `${scenario.rate.toFixed(2)}%` : "—"}</td><td className={`py-3 text-right font-medium ${scenario.marginRate !== null && scenario.marginRate < 0 ? "text-destructive" : ""}`}>{scenario.marginRate === null ? "원가 미입력" : `${scenario.marginRate.toFixed(2)}%`}</td><td className="py-3 pl-4 text-muted-foreground">{scenario.note}</td></tr>)}</tbody></table>{cost > 0 && scenarios.some(row => row.key !== "floor" && row.price < (calculateBidFloor(cost, margin) ?? 0)) ? <p className="mt-3 flex items-start gap-2 rounded-lg bg-amber-50 p-3 text-xs leading-5 text-amber-900 dark:bg-amber-950/30 dark:text-amber-200"><AlertTriangle className="mt-0.5 h-4 w-4 shrink-0" />일부 통계 시나리오가 입력한 목표 마진 하한선보다 낮습니다. 원가, 부대비용, 계약 조건 및 경쟁 상황을 별도로 검토하세요.</p> : null}</CardContent></Card>;
}

export function BidRateTrend({ points, isLoading }: { points: TrendPoint[] | undefined; isLoading: boolean }) {
  if (isLoading) return <Card className="border-0 shadow-sm"><CardContent className="py-10 text-sm text-muted-foreground">낙찰률 추세를 집계하는 중입니다.</CardContent></Card>;
  if (!points?.length) return <Card className="border-0 shadow-sm"><CardHeader className="pb-2"><CardTitle className="flex items-center gap-2 text-base"><ChartNoAxesCombined className="h-4 w-4 text-primary" />과거 낙찰률 추세</CardTitle></CardHeader><CardContent className="py-8 text-sm text-muted-foreground">현재 조건에 날짜가 있는 낙찰 표본이 부족해 추세를 표시할 수 없습니다.</CardContent></Card>;
  const values = points.map(point => point.averageRate); const min = Math.min(...values); const max = Math.max(...values); const span = Math.max(max - min, 0.5); const width = 620; const height = 210; const padding = 28; const x = (index: number) => padding + (points.length === 1 ? (width - padding * 2) / 2 : index * (width - padding * 2) / (points.length - 1)); const y = (rate: number) => height - padding - ((rate - (min - span * 0.15)) / (span * 1.3)) * (height - padding * 2); const line = points.map((point, index) => `${x(index)},${y(point.averageRate)}`).join(" ");
  return <Card className="border-0 shadow-sm"><CardHeader className="pb-2"><CardTitle className="flex items-center gap-2 text-base"><ChartNoAxesCombined className="h-4 w-4 text-primary" />과거 낙찰률 추세</CardTitle><p className="text-xs font-normal text-muted-foreground">현재 기관·품목 조건의 최근 {points.length}개 일자별 평균 낙찰률입니다.</p></CardHeader><CardContent><div className="overflow-x-auto"><svg viewBox={`0 0 ${width} ${height}`} className="h-52 min-w-[520px] w-full" role="img" aria-label="과거 낙찰률 일별 추세 그래프"><line x1={padding} x2={width - padding} y1={height - padding} y2={height - padding} stroke="currentColor" className="text-border" /><line x1={padding} x2={padding} y1={padding} y2={height - padding} stroke="currentColor" className="text-border" /><polyline points={line} fill="none" stroke="currentColor" strokeWidth="3" strokeLinejoin="round" strokeLinecap="round" className="text-primary" />{points.map((point, index) => <g key={point.date}><circle cx={x(index)} cy={y(point.averageRate)} r="4" className="fill-primary" /><text x={x(index)} y={height - 7} textAnchor="middle" className="fill-muted-foreground text-[10px]">{point.date.slice(5).replace("-", "/")}</text><text x={x(index)} y={Math.max(16, y(point.averageRate) - 9)} textAnchor="middle" className="fill-foreground text-[10px]">{point.averageRate.toFixed(1)}%</text><title>{`${point.date}: 평균 ${point.averageRate.toFixed(2)}%, ${point.count}건`}</title></g>)}</svg></div><div className="mt-2 flex justify-between text-xs text-muted-foreground"><span>최저 {min.toFixed(2)}%</span><span>최고 {max.toFixed(2)}%</span></div></CardContent></Card>;
}
