import { createRequire } from "node:module";

// The Vercel Node builder traces only this function's dependency graph. This
// CJS bundle is generated by `pnpm build:vercel`, keeping all server imports
// inside the function package instead of relying on `/var/task/server`.
const require = createRequire(import.meta.url);
const { createRuntimeApp } = require("./runtimeApp.cjs") as typeof import("../server/runtimeApp");

// Vercel maps this catch-all function to every /api/* route. The existing
// tRPC, OAuth, storage and cron handlers retain their public URL structure.
const app = createRuntimeApp("vercel");

export default app;
